FROM bitnami/postgresql:latest
EXPOSE 5432

# Configuration avec les variables d'environnement
ARG POSTGRES_USER
ARG POSTGRES_DB

ENV POSTGRES_USER=${POSTGRES_USER}
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=${POSTGRES_DB}

VOLUME ["/bitnami/postgresql"]
