FROM mcr.microsoft.com/dotnet/sdk:7.0 
COPY worker/ .
EXPOSE 80
EXPOSE 443
# Variables d'environnement pour postgres
ARG PG_HOST
ARG PG_PORT
ARG PG_USER
ARG PG_PASSWORD
ARG PG_DB

ARG REDIS_HOST

ENV PG_HOST=${PG_HOST}
ENV PG_PORT=${PG_PORT}
ENV PG_USER=${PG_USER}
ENV PG_PASSWORD=${PG_PASSWORD}
ENV PG_DB=${PG_DB}

#Pareil pour redis
ENV REDIS_HOST=${REDIS_HOST}

# Trying out something that doesn't take eons to compile itself
# RUN dotnet restore
# RUN dotnet publish -c release --self-contained false --no-restore
ENTRYPOINT dotnet bin/release/net7.0/Worker.dll
